# Generated by Django 5.1.9 on 2025-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='activities',
            field=models.TextField(blank=True, help_text='Atividades realizadas na classe (para mensagens de rotina diária).', null=True, verbose_name='Atividades na Classe'),
        ),
        migrations.AddField(
            model_name='message',
            name='homework',
            field=models.TextField(blank=True, help_text='Tarefa de casa (para mensagens de rotina diária).', null=True, verbose_name='Tarefa de Casa'),
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a mensagem estará disponível.', null=True, verbose_name='Data e Hora Agendada'),
        ),
    ]
