# Generated by Django 5.1.9 on 2025-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_activities_message_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='context',
            field=models.TextField(blank=True, help_text='Conteúdo da mensagem.', null=True, verbose_name='Conteúdo'),
        ),
    ]
