# Generated by Django 5.1.7 on 2025-04-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messagereadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetype',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
