# Generated by Django 5.1.8 on 2025-05-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_messagetype_color'),
        ('school', '0002_alter_class_grade_alter_class_is_regular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereadlog',
            options={'verbose_name': 'Log de Leitura', 'verbose_name_plural': 'Logs de Leitura'},
        ),
        migrations.AlterModelOptions(
            name='receivedmessage',
            options={'verbose_name': 'Recebida', 'verbose_name_plural': 'Recebidas'},
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, help_text='Arquivo anexo à mensagem (opcional).', null=True, upload_to='attachments/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Turmas para as quais a mensagem será enviada.', related_name='messages', to='school.class', verbose_name='Turmas'),
        ),
        migrations.AlterField(
            model_name='message',
            name='context',
            field=models.TextField(help_text='Conteúdo da mensagem.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi criada.', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(help_text='Usuário responsável pela criação da mensagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem associada à mensagem (opcional).', null=True, upload_to='messages/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(help_text='Título da mensagem.', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Tipo de mensagem (ex: Aviso, Urgente, Informação).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.messagetype', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Usuários específicos que receberão a mensagem.', related_name='individual_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
        migrations.AlterField(
            model_name='messagereadlog',
            name='message',
            field=models.ForeignKey(help_text='Mensagem que foi lida.', on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='messagereadlog',
            name='read',
            field=models.BooleanField(default=True, help_text='Indica se a mensagem foi lida (sempre True).', verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='messagereadlog',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da leitura.', verbose_name='Data de Leitura'),
        ),
        migrations.AlterField(
            model_name='messagereadlog',
            name='user',
            field=models.ForeignKey(help_text='Usuário que leu a mensagem.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='color',
            field=models.CharField(default='#000000', help_text='Cor associada ao tipo de mensagem (formato HEX, ex: #FF0000).', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional do tipo de mensagem.', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='name',
            field=models.CharField(help_text='Nome do tipo de mensagem (ex: Aviso, Recado, Urgente).', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='message',
            field=models.ForeignKey(help_text='Mensagem recebida.', on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='message.message', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='read',
            field=models.BooleanField(default=False, help_text='Indica se a mensagem foi lida pelo destinatário.', verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data em que a mensagem foi disponibilizada.', verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='recipient',
            field=models.ForeignKey(help_text='Usuário que recebeu a mensagem.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
    ]
