# Generated by Django 5.1.9 on 2025-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, help_text='Título da mensagem.', max_length=255, null=True, verbose_name='Título'),
        ),
    ]
