# Generated by Django 5.1.9 on 2025-06-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='message_gallery/', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='message.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Imagem da Mensagem',
                'verbose_name_plural': 'Imagens da Mensagem',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
