# Generated by Django 5.1.8 on 2025-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_event'),
        ('school', '0004_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='classes',
            field=models.ManyToManyField(related_name='events', to='school.class'),
        ),
    ]
