# Generated by Django 5.1.7 on 2025-03-28 13:10

import a_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[a_users.models.validate_cpf]),
        ),
    ]
