# Generated by Django 5.1.9 on 2025-05-20 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria (ex: Literatura, Ciências, História).', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do livro ou documento.', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional sobre o conteúdo do documento.', verbose_name='Descrição')),
                ('file', models.FileField(help_text='Arquivo PDF do livro ou documento.', upload_to='books/pdfs/', verbose_name='Arquivo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa ou visualização do documento.', null=True, upload_to='books/pdfs/thumbs/', verbose_name='Miniatura')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o documento foi enviado.', verbose_name='Data de Envio')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categorias associadas ao documento.', to='books.category', verbose_name='Categorias')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='Classes específicas que devem receber o documento.', related_name='documents', to='school.class', verbose_name='Classes Alvo')),
                ('target_grades', models.ManyToManyField(blank=True, help_text='Séries escolares para as quais o documento é destinado.', related_name='documents', to='school.grade', verbose_name='Séries Alvo')),
                ('target_users', models.ManyToManyField(blank=True, help_text='Usuários específicos que devem receber o documento.', related_name='individual_documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo')),
                ('uploaded_by', models.ForeignKey(help_text='Usuário responsável pelo envio do documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Livro-Documento',
                'verbose_name_plural': 'Livros-Documentos',
            },
        ),
        migrations.CreateModel(
            name='ReceivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, help_text='Indica se o documento foi lido pelo destinatário.', verbose_name='Lido')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Data em que o documento foi disponibilizado ao usuário.', verbose_name='Data de Recebimento')),
                ('document', models.ForeignKey(help_text='Documento recebido pelo usuário.', on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='books.document', verbose_name='Documento')),
                ('recipient', models.ForeignKey(help_text='Usuário que recebeu o documento.', on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Recebido',
                'verbose_name_plural': 'Recebidos',
            },
        ),
        migrations.CreateModel(
            name='DocumentReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True, help_text='Indica se o documento foi lido (valor padrão: True).', verbose_name='Lido')),
                ('read_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da leitura do documento.', verbose_name='Data de Leitura')),
                ('document', models.ForeignKey(help_text='Documento que foi lido.', on_delete=django.db.models.deletion.CASCADE, to='books.document', verbose_name='Documento')),
                ('user', models.ForeignKey(help_text='Usuário que leu o documento.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Leitura',
                'verbose_name_plural': 'Logs de Leitura',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
