# Generated by Django 5.1.8 on 2025-05-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_document_thumbnail'),
        ('school', '0002_alter_class_grade_alter_class_is_regular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Livro-Documento', 'verbose_name_plural': 'Livros-Documentos'},
        ),
        migrations.AlterModelOptions(
            name='documentreadlog',
            options={'verbose_name': 'Log de Leitura', 'verbose_name_plural': 'Logs de Leitura'},
        ),
        migrations.AlterModelOptions(
            name='receiveddocument',
            options={'verbose_name': 'Recebido', 'verbose_name_plural': 'Recebidos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome da categoria (ex: Literatura, Ciências, História).', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias associadas ao documento.', to='books.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional sobre o conteúdo do documento.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Arquivo PDF do livro ou documento.', upload_to='books/pdfs/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes específicas que devem receber o documento.', related_name='documents', to='school.class', verbose_name='Classes Alvo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_grades',
            field=models.ManyToManyField(blank=True, help_text='Séries escolares para as quais o documento é destinado.', related_name='documents', to='school.grade', verbose_name='Séries Alvo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Usuários específicos que devem receber o documento.', related_name='individual_documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagem de capa ou visualização do documento.', null=True, upload_to='books/pdfs/thumbs/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='Título do livro ou documento.', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o documento foi enviado.', verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Usuário responsável pelo envio do documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='documentreadlog',
            name='document',
            field=models.ForeignKey(help_text='Documento que foi lido.', on_delete=django.db.models.deletion.CASCADE, to='books.document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentreadlog',
            name='read',
            field=models.BooleanField(default=True, help_text='Indica se o documento foi lido (valor padrão: True).', verbose_name='Lido'),
        ),
        migrations.AlterField(
            model_name='documentreadlog',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da leitura do documento.', verbose_name='Data de Leitura'),
        ),
        migrations.AlterField(
            model_name='documentreadlog',
            name='user',
            field=models.ForeignKey(help_text='Usuário que leu o documento.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='receiveddocument',
            name='document',
            field=models.ForeignKey(help_text='Documento recebido pelo usuário.', on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='books.document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='receiveddocument',
            name='read',
            field=models.BooleanField(default=False, help_text='Indica se o documento foi lido pelo destinatário.', verbose_name='Lido'),
        ),
        migrations.AlterField(
            model_name='receiveddocument',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data em que o documento foi disponibilizado ao usuário.', verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='receiveddocument',
            name='recipient',
            field=models.ForeignKey(help_text='Usuário que recebeu o documento.', on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
    ]
