# Generated by Django 5.1.8 on 2025-05-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('html_path', models.CharField(help_text='Ex: collections/html/nome_da_pasta/index.html', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='collections/thumbs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='collection.category')),
                ('target_classes', models.ManyToManyField(blank=True, related_name='collections', to='school.class')),
                ('target_grades', models.ManyToManyField(blank=True, related_name='collections', to='school.grade')),
                ('target_users', models.ManyToManyField(blank=True, related_name='individual_collections', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
