# Generated by Django 5.1.9 on 2025-05-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria (ex: Matemática, Ciências, Jogos Educativos).', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do conteúdo ou jogo.', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional do conteúdo ou jogo.', verbose_name='Descrição')),
                ('html_path', models.CharField(help_text='Ex: collections/html/nome_da_pasta/index.html', max_length=255, verbose_name='Caminho HTML')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa ou miniatura do conteúdo.', null=True, upload_to='collections/thumbs/', verbose_name='Miniatura')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o conteúdo foi enviado.', verbose_name='Data de Envio')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categorias associadas a este conteúdo.', to='collection.category', verbose_name='Categorias')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='Classes escolares específicas que devem receber o conteúdo.', related_name='collections', to='school.class', verbose_name='Classes Alvo')),
                ('target_grades', models.ManyToManyField(blank=True, help_text='Séries escolares para as quais este conteúdo é direcionado.', related_name='collections', to='school.grade', verbose_name='Séries Alvo')),
                ('target_users', models.ManyToManyField(blank=True, help_text='Usuários específicos que devem receber este conteúdo.', related_name='individual_collections', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo')),
                ('uploaded_by', models.ForeignKey(help_text='Usuário responsável pelo envio do conteúdo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Jogo-Coleção',
                'verbose_name_plural': 'Jogos-Coleções',
            },
        ),
    ]
