# Generated by Django 5.1.8 on 2025-05-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_grade_schoolclass'),
        ('school', '0002_alter_class_grade_alter_class_is_regular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'verbose_name': 'Jogo-Coleção', 'verbose_name_plural': 'Jogos-Coleções'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome da categoria (ex: Matemática, Ciências, Jogos Educativos).', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias associadas a este conteúdo.', to='collection.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional do conteúdo ou jogo.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='html_path',
            field=models.CharField(help_text='Ex: collections/html/nome_da_pasta/index.html', max_length=255, verbose_name='Caminho HTML'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes escolares específicas que devem receber o conteúdo.', related_name='collections', to='school.class', verbose_name='Classes Alvo'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='target_grades',
            field=models.ManyToManyField(blank=True, help_text='Séries escolares para as quais este conteúdo é direcionado.', related_name='collections', to='school.grade', verbose_name='Séries Alvo'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Usuários específicos que devem receber este conteúdo.', related_name='individual_collections', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagem de capa ou miniatura do conteúdo.', null=True, upload_to='collections/thumbs/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='title',
            field=models.CharField(help_text='Título do conteúdo ou jogo.', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o conteúdo foi enviado.', verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Usuário responsável pelo envio do conteúdo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
    ]
