# Generated by Django 5.1.9 on 2025-05-20 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do papel ou função (ex: Professor, Responsável, Aluno).', max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional do papel.', null=True, verbose_name='Descrição')),
                ('can_post', models.BooleanField(default=True, help_text='Indica se esse papel tem permissão para criar postagens.', verbose_name='Pode Postar')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 1º Ano, 6ª Série', max_length=50, unique=True, verbose_name='Nome da Série')),
                ('colaborator', models.ManyToManyField(blank=True, help_text='Usuários com papel de colaborador nesta série', related_name='colaborated_grades', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores de Série')),
                ('coordinators', models.ManyToManyField(blank=True, help_text='Usuários com papel de coordenação nesta série', related_name='coordinated_grades', to=settings.AUTH_USER_MODEL, verbose_name='Coordenadores')),
                ('directors', models.ManyToManyField(blank=True, help_text='Usuários com papel de direção nesta série', related_name='directed_grades', to=settings.AUTH_USER_MODEL, verbose_name='Diretores de Série')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificador único da turma (ex: Turma A, 6º Ano B).', max_length=50, verbose_name='Turma')),
                ('is_regular', models.BooleanField(default=True, help_text='Indica se esta é uma turma regular.', verbose_name='Turma Regular')),
                ('academic_year', models.PositiveSmallIntegerField(default=2025, help_text='Ano de referência para a turma.', verbose_name='Ano Letivo')),
                ('teachers', models.ManyToManyField(help_text='Professores responsáveis por esta turma.', related_name='classrooms_taught', to=settings.AUTH_USER_MODEL, verbose_name='Professores')),
                ('grade', models.ForeignKey(help_text='Séries escolares associada à turma.', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.grade', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('name', 'grade', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_assigned', models.ManyToManyField(help_text='Turmas nas quais o aluno está matriculado.', related_name='students', to='school.class', verbose_name='Turmas')),
                ('user', models.OneToOneField(help_text='Usuário correspondente ao aluno.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('children', models.ManyToManyField(related_name='parents', to='school.student', verbose_name='Filhos')),
            ],
            options={
                'verbose_name': 'Pai/Mãe',
                'verbose_name_plural': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da disciplina, como Matemática, História ou Ciências.', max_length=100, verbose_name='Nome da Disciplina')),
                ('code', models.CharField(help_text='Código único para a disciplina.', max_length=20, unique=True, verbose_name='Código')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.grade', verbose_name='Série')),
                ('teachers', models.ManyToManyField(related_name='subjects_taught', to=settings.AUTH_USER_MODEL, verbose_name='Professores')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'unique_together': {('name', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(help_text='Papel atribuído ao usuário.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='school.role', verbose_name='Papel')),
                ('user', models.ForeignKey(help_text='Usuário associado ao papel.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Papel Geral do Usuário',
                'verbose_name_plural': 'Papéis Gerais dos Usuários',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
