# Generated by Django 5.1.8 on 2025-05-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(help_text='Série escolar associada à classe.', on_delete=django.db.models.deletion.CASCADE, to='school.grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_regular',
            field=models.BooleanField(default=True, help_text='Indica se esta classe é uma classe regular.', verbose_name='Classe Regular'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Nome ou código identificador da classe (ex: Turma A, 6B).', max_length=50, verbose_name='Nome da Classe'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(help_text='Professores responsáveis por esta classe.', related_name='classes_taught', to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(help_text='Nome da série escolar (ex: 1º Ano, 6ª Série).', max_length=50, verbose_name='Nome da Série'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(help_text='Alunos associados a este responsável.', related_name='parents', to='school.student', verbose_name='Filhos'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(help_text='Usuário do pai, mãe ou responsável.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_post',
            field=models.BooleanField(default=True, help_text='Indica se esse papel tem permissão para criar postagens.', verbose_name='Pode Postar'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Nome do papel ou função (ex: Professor, Responsável, Aluno).', max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes_assigned',
            field=models.ManyToManyField(help_text='Classes nas quais o aluno está matriculado.', related_name='students', to='school.class', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='Usuário correspondente ao aluno.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='Papel atribuído ao usuário.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='school.role', verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='Usuário associado ao papel.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
