# Generated by Django 5.1.7 on 2025-03-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Pai/Mãe', 'verbose_name_plural': 'Pais'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Papel', 'verbose_name_plural': 'Papéis'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
