# Generated by Django 5.1.7 on 2025-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_send_messages',
            field=models.BooleanField(default=False),
        ),
    ]
