# Generated by Django 5.1.8 on 2025-05-13 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_parent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da disciplina, como Matemática, História ou Ciências.', max_length=100, verbose_name='Nome da Disciplina')),
                ('code', models.CharField(help_text='Código único para a disciplina.', max_length=20, unique=True, verbose_name='Código')),
                ('grade', models.ForeignKey(help_text='Série à qual essa disciplina pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.grade', verbose_name='Série')),
                ('teachers', models.ManyToManyField(help_text='Professores que lecionam essa disciplina.', related_name='subjects_taught', to=settings.AUTH_USER_MODEL, verbose_name='Professores')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'unique_together': {('name', 'grade')},
            },
        ),
    ]
