# Generated by Django 5.1.7 on 2025-03-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Permissão por perfil', 'verbose_name_plural': 'Permissão por perfil'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'Associar usuário com função'},
        ),
    ]
