# Generated by Django 5.1.8 on 2025-05-15 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='coordinators',
            field=models.ManyToManyField(help_text='Coordenadores responsáveis por esta série.', related_name='coordinated_grades', to=settings.AUTH_USER_MODEL, verbose_name='Coordenadores'),
        ),
    ]
