# Generated by Django 5.1.8 on 2025-05-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_grade_coordinators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='coordinators',
        ),
    ]
