# Generated by Django 5.1.8 on 2025-05-16 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_grade_coordinators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': [('global_director_access', 'Acesso completo de diretor a todas as séries')], 'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2025, help_text='Ano de referência para a turma', verbose_name='Ano Letivo'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(help_text='Série escolar associada à turma.', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_regular',
            field=models.BooleanField(default=True, help_text='Indica se esta é uma turma regular.', verbose_name='Turma Regular'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Identificador único da turma (ex: Turma A, 6º Ano B).', max_length=50, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(help_text='Professores responsáveis por esta turma.', related_name='classrooms_taught', to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes_assigned',
            field=models.ManyToManyField(help_text='Turmas nas quais o aluno está matriculado.', related_name='students', to='school.class', verbose_name='Turmas'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'grade', 'academic_year')},
        ),
        migrations.CreateModel(
            name='GradeCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CO', 'Coordenador'), ('DI', 'Diretor de Série')], default='CO', max_length=2, verbose_name='Tipo de Cargo')),
                ('start_date', models.DateField(help_text='Data de início do exercício do cargo', verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Opcional - data de término do exercício do cargo', null=True, verbose_name='Data de Término')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade', verbose_name='Série')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Designação de Cargo',
                'verbose_name_plural': 'Designações de Cargos',
                'unique_together': {('user', 'grade', 'role')},
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='coordinators',
            field=models.ManyToManyField(help_text='Designação de coordenadores e diretores para esta série', related_name='coordinated_grades', through='school.GradeCoordinator', to=settings.AUTH_USER_MODEL, verbose_name='Cargos'),
        ),
    ]
