# Generated by Django 5.1.8 on 2025-05-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_class_options_alter_grade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Papel Geral do Usuário', 'verbose_name_plural': 'Papéis Gerais dos Usuários'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinated_grades', through='school.GradeCoordinator', to=settings.AUTH_USER_MODEL, verbose_name='Designações'),
        ),
        migrations.AlterField(
            model_name='gradecoordinator',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='gradecoordinator',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_coordinators', to='school.grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='gradecoordinator',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='gradecoordinator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_coordinations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
