# Generated by Django 5.1.9 on 2025-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mensage', models.TextField(verbose_name='Mensagem')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Telefone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
            ],
        ),
    ]
