# Generated by Django 5.1.7 on 2025-03-28 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fique por dentro das novidades!', max_length=255)),
                ('description', models.TextField(default='Confira os últimos artigos e não perca as atualizações mais importantes.')),
                ('btn_texto', models.CharField(default='Ver Artigos →', max_length=50)),
                ('btn_link', models.URLField(default='#blog')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cta_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/', verbose_name='Imagem')),
                ('short_description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descrição Curta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('star', models.BooleanField(default=False, verbose_name='Especial')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categories', models.ManyToManyField(blank=True, to='blog.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
