# Generated by Django 5.1.8 on 2025-05-09 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True, help_text='Marque para que a postagem apareça no site.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Selecione uma ou mais categorias para classificar a postagem.', to='blog.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a postagem foi criada.', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, help_text='Conteúdo principal da postagem.', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da postagem (não editável).', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Imagem de capa da postagem.', null=True, upload_to='images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(help_text='Título da postagem.', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela publicação.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(blank=True, help_text='Resumo breve da postagem (aparece em listagens ou destaques).', max_length=2000, null=True, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='star',
            field=models.BooleanField(default=False, help_text='Marque se esta postagem for um destaque ou recomendada.', verbose_name='Especial'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='active',
            field=models.BooleanField(default=True, help_text='Marque para exibir essa chamada no site.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='btn_link',
            field=models.URLField(default='#blog', help_text='URL de destino ao clicar no botão.', verbose_name='Link do Botão'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='btn_texto',
            field=models.CharField(default='Ver Artigos →', help_text='Texto que aparecerá no botão de ação (ex: "Ver mais").', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=models.TextField(default='Confira os últimos artigos e não perca as atualizações mais importantes.', help_text='Escreva um texto breve que descreva a chamada.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem opcional para ilustrar a chamada.', null=True, upload_to='cta_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.CharField(default='Fique por dentro das novidades!', help_text='Digite um título chamativo para a chamada de atenção.', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional sobre a categoria.', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome da categoria do blog.', max_length=255, verbose_name='Nome'),
        ),
    ]
