# Generated by Django 5.1.9 on 2025-05-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('performance', models.TextField(blank=True, null=True, verbose_name='Desempenho')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('weight', models.IntegerField(default=1, verbose_name='Peso')),
                ('date', models.DateField(verbose_name='Data')),
                ('evaluation_period', models.CharField(choices=[('livre', 'Livre'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('mensal', 'Mensal'), ('quadremestral', 'Quadremestral'), ('contínua', 'Contínua'), ('unidade', 'Por Unidade')], default='bimestral', max_length=20, verbose_name='Período de Avaliação')),
                ('attachment', models.FileField(blank=True, help_text='Arquivo opcional enviado com a mensagem.', null=True, upload_to='note_attachments/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
