# Generated by Django 5.1.8 on 2025-05-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Avaliação')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Avaliação')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
