# Generated by Django 5.1.8 on 2025-05-13 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comentário')),
                ('visible_to_parent', models.BooleanField(default=True, verbose_name='Visível aos Pais?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('note_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.note', verbose_name='Registro de Desempenho')),
            ],
            options={
                'verbose_name': 'Comentário de Desempenho',
                'verbose_name_plural': 'Comentários de Desempenho',
            },
        ),
    ]
