# Generated by Django 5.1.8 on 2025-05-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='class_group',
        ),
    ]
