# Generated by Django 5.1.8 on 2025-05-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_note_class_group'),
        ('school', '0004_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='note',
            name='performance',
            field=models.TextField(blank=True, null=True, verbose_name='Desempenho'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='note',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Peso'),
        ),
        migrations.DeleteModel(
            name='NoteComment',
        ),
    ]
