# Generated by Django 5.1.8 on 2025-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_options_remove_note_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota'),
        ),
    ]
