# Generated by Django 5.1.8 on 2025-05-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_note_evaluation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, help_text='Arquivo opcional enviado com a mensagem.', null=True, upload_to='note_attachments/', verbose_name='Anexo'),
        ),
    ]
