# Generated by Django 5.1.9 on 2025-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Informe o título do link que aparecerá no header.', max_length=50, verbose_name='Título do Link')),
                ('url', models.CharField(help_text='Informe a URL do link ex: ( / )', max_length=200, verbose_name='URL do Link')),
                ('is_active', models.BooleanField(default=True, help_text='Habilite ou desabilite o link', verbose_name='É ativo?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Informe a sequência que o link que aparecerá no header.', verbose_name='Sequência do Link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['order'],
            },
        ),
    ]
