# Generated by Django 5.1.8 on 2025-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ['order'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Habilite ou desabilite o link', verbose_name='É ativo?'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Informe a sequência que o link que aparecerá no header.', verbose_name='Sequência do Link'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='title',
            field=models.CharField(help_text='Informe o título do link que aparecerá no header.', max_length=50, verbose_name='Título do Link'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(help_text='Informe a URL do link ex: ( / )', max_length=200, verbose_name='URL do Link'),
        ),
    ]
