# Generated by Django 5.1.7 on 2025-03-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
