# Generated by Django 5.1.9 on 2025-05-20 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificador da categoria de ticket.', max_length=100, unique=True, verbose_name='Nome da categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Categoria de Ticket',
                'verbose_name_plural': 'Categorias de Ticket',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketAllowedResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Usuário autorizado a responder tickets.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('categories', models.ManyToManyField(help_text='Categorias que este usuário pode responder.', related_name='allowed_responders', to='ticket.ticketcategory', verbose_name='Categorias permitidas')),
            ],
            options={
                'verbose_name': 'Permissão de resposta',
                'verbose_name_plural': 'Permissões de respostas',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Assunto principal do ticket.', max_length=255, verbose_name='Assunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('closed', 'Fechado')], default='open', help_text='Status atual do ticket.', max_length=20, verbose_name='Status')),
                ('ticket_number', models.CharField(help_text='Número único de identificação do ticket.', max_length=20, unique=True, verbose_name='Número do ticket')),
                ('parent', models.ForeignKey(help_text='Responsável que abriu o ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='school.parent', verbose_name='Responsável')),
                ('category', models.ForeignKey(blank=True, default='Acadêmico/Pedagógico', help_text='Categoria à qual o ticket pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.ticketcategory', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Conteúdo da mensagem enviada.', verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('attachment', models.FileField(blank=True, help_text='Arquivo opcional enviado com a mensagem.', null=True, upload_to='ticket_attachments/', verbose_name='Anexo')),
                ('sender', models.ForeignKey(help_text='Usuário que enviou a mensagem.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('ticket', models.ForeignKey(help_text='Ticket ao qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='Ticket')),
            ],
        ),
    ]
