# Generated by Django 5.1.8 on 2025-05-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_parent_user'),
        ('ticket', '0002_ticketcategory_ticket_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketallowedresponder',
            options={'verbose_name': 'Permissão de resposta', 'verbose_name_plural': 'Permissões de respostas'},
        ),
        migrations.AddField(
            model_name='ticketallowedresponder',
            name='categories',
            field=models.ManyToManyField(help_text='Categorias que este usuário pode responder.', related_name='allowed_responders', to='ticket.ticketcategory', verbose_name='Categorias permitidas'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria à qual o ticket pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.ticketcategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(help_text='Responsável que abriu o ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='school.parent', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('closed', 'Fechado')], default='open', help_text='Status atual do ticket.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(help_text='Assunto principal do ticket.', max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(help_text='Número único de identificação do ticket.', max_length=20, unique=True, verbose_name='Número do ticket'),
        ),
        migrations.AlterField(
            model_name='ticketallowedresponder',
            name='user',
            field=models.ForeignKey(help_text='Usuário autorizado a responder tickets.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(help_text='Nome identificador da categoria de ticket.', max_length=100, unique=True, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Arquivo opcional enviado com a mensagem.', null=True, upload_to='ticket_attachments/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de envio'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(help_text='Conteúdo da mensagem enviada.', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(help_text='Usuário que enviou a mensagem.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket ao qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='Ticket'),
        ),
    ]
