# Generated by Django 5.1.8 on 2025-05-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketallowedresponder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, default='Acadêmico/Pedagógico', help_text='Categoria à qual o ticket pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.ticketcategory', verbose_name='Categoria'),
        ),
    ]
